/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project_model.NhanVien;
import project_model.NhanVien_Model;

/**
 *
 * @author Hoàng Huy
 */
public class Form_Main extends javax.swing.JFrame {
    String filename = null;
    byte[] person_img = null;
    DefaultTableModel tb_Model;
    List<NhanVien> listNV;

    /**
     * Creates new form Form_Main
     */
    public Form_Main() {
        initComponents();
        setLocationRelativeTo(null);
        setTable();
        setTitle("Quản lý nhân viên");
    }

    public void setTable() {
        String colum[] = {"Mã Nhân Viên", "Họ tên", "Giới tính", "Ngày sinh", "SĐT", "Email", "Địa chỉ", "Phòng ban", "Chức vụ", "Lương cơ bản", "Hệ số", "Giờ tăng ca", "Ngày nghỉ", "Thưởng", "Tổng"};
        tb_Model = new DefaultTableModel();
        tb_Model.setColumnIdentifiers(colum);
        tblNhanVien.setModel(tb_Model);
    }

    public void dataTable() throws Exception {
        NhanVien_Model nvm = new NhanVien_Model();
        listNV = nvm.load(); // Dùng để lấy dữ liệu từ CSDL để in lên bảng
        String gioitinh = null;
        while (tb_Model.getRowCount() > 0) {
            tb_Model.removeRow(0);
        }
        for (NhanVien nv : listNV) {
            if (nv.getGioitinh() == 1) {
                gioitinh = "Nam";
            } else {
                gioitinh = "Nữ";
            }
            tb_Model.addRow(new String[]{nv.getMaNV(), nv.getHoten(), gioitinh, nv.getNgaysinh().toString(), nv.getSdt(), nv.getEmail(), nv.getDiachi(), nv.getPhongban(), nv.getChucvu(),
                nv.getLuongcoban(), nv.getHeso(), nv.getGiotangca(), nv.getSongaynghi(), nv.getThuong(), nv.getTong()});
        }
        tb_Model.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabThongtin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnNhapmoi = new javax.swing.JButton();
        txtMaNV = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        txtSdt = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        cboPhongBan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnChonanh = new javax.swing.JButton();
        txtanh = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        btnTimkiem = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cboChucvu = new javax.swing.JComboBox<>();
        txtcanhbao_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtLuongcoban = new javax.swing.JTextField();
        txtHeso = new javax.swing.JTextField();
        txtGiotangca = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNgaynghir = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTHuong = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtTongNhan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Thông tin cá nhân");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Giới tính:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ngày sinh:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Điện thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Phòng ban:");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Actions-list-add-user-icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Apps-system-software-update-icon.png"))); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Actions-list-remove-user-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Printer-icon.png"))); // NOI18N
        btnIn.setText("In");

        btnNhapmoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/App-Quick-restart-icon.png"))); // NOI18N
        btnNhapmoi.setText("Nhập mới");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(54, 54, 54)
                .addComponent(btnNhapmoi)
                .addGap(59, 59, 59)
                .addComponent(btnSua)
                .addGap(59, 59, 59)
                .addComponent(btnXoa)
                .addGap(59, 59, 59)
                .addComponent(btnIn)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnNhapmoi)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnIn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbNam.setText("Nam");

        buttonGroup1.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbNu.setText("Nữ");

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDiachi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboPhongBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboPhongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài chính", "Kỹ Thuật", "Nhân sự" }));
        cboPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhongBanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Họ tên:");

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ảnh nhân viên:");

        btnChonanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChonanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Upload-Folder-Graphite-icon.png"))); // NOI18N
        btnChonanh.setText("Chọn ảnh");
        btnChonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonanhActionPerformed(evt);
            }
        });

        txtanh.setBackground(new java.awt.Color(255, 51, 0));

        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/Zoom-icon (1).png"))); // NOI18N
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Chức vụ:");

        cboChucvu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trưởng phòng", "Nhân viên" }));

        txtcanhbao_img.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtcanhbao_img.setForeground(new java.awt.Color(255, 51, 51));
        txtcanhbao_img.setText("*Ảnh chưa được cập nhật");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboPhongBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMail)
                                    .addComponent(txtSdt)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rdbNam)
                                                .addGap(14, 14, 14)
                                                .addComponent(rdbNu))
                                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanh, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcanhbao_img))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChonanh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel9))
                    .addComponent(btnTimkiem)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdbNam)
                            .addComponent(rdbNu)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcanhbao_img)
                            .addComponent(jLabel10))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cboChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtanh, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonanh)
                        .addGap(27, 27, 27)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        tblNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_JAVApro/logout-icon.png"))); // NOI18N
        jButton7.setText("Đăng xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Lương cơ bản:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Hệ số:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Giờ tăng ca:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Số ngày nghỉ:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Thưởng:");

        txtLuongcoban.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtHeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtGiotangca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("/Tháng");

        txtNgaynghir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Ngày");

        txtTHuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTHuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTHuongActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("Tổng nhận:");

        txtTongNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("* Ấn Enter để hiện tổng nhận");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNgaynghir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(txtLuongcoban)
                    .addComponent(txtHeso)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGiotangca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addComponent(txtTHuong, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(170, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLuongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtHeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtGiotangca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNgaynghir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTHuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTongNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("Lương thưởng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabThongtinLayout = new javax.swing.GroupLayout(tabThongtin);
        tabThongtin.setLayout(tabThongtinLayout);
        tabThongtinLayout.setHorizontalGroup(
            tabThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThongtinLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabThongtinLayout.setVerticalGroup(
            tabThongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabThongtinLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("", tabThongtin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Thông tin");

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public int kiemtraPhongBan(String ban){
//       if(ban.equals("Item 1")) return 0;
//       else if(ban.equals("Item 2")) return 1;
//       else if(ban.equals("Item 3")) return 2;
//       else  return 3;
//    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            dataTable();
            txtcanhbao_img.setVisible(false);
            ImageIcon img_default = new ImageIcon("C:\\Users\\huyb1\\Downloads\\Tải xuống\\nhanvien.jpg");
            txtanh.setIcon(img_default);
        } catch (Exception ex) {
            Logger.getLogger(Form_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn thoát ?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        if (txtMaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !");
            txtMaNV.setBackground(Color.yellow);
            txtMaNV.requestFocus();
            return;
        } else {
            txtMaNV.setBackground(Color.white);
        }
        try {
            NhanVien_Model nvm = new NhanVien_Model();
            if (nvm.timkiem(txtMaNV.getText()) != null) {
                NhanVien nv = nvm.timkiem(txtMaNV.getText());
                txtMaNV.setText(nv.getMaNV().trim());
                txtDiachi.setText(nv.getDiachi().trim());
                txtHoten.setText(nv.getHoten().trim());
                txtMail.setText(nv.getEmail().trim());
                txtSdt.setText(nv.getSdt().trim());
                if (nv.getGioitinh() == 1) {
                    rdbNam.setSelected(true);
                } else {
                    rdbNu.setSelected(true);
                }
                jdate.setDate(nv.getNgaysinh());
                cboPhongBan.setSelectedItem(nv.getPhongban());
                cboChucvu.setSelectedItem(nv.getChucvu());
                txtLuongcoban.setText(nv.getLuongcoban().trim());
                txtHeso.setText(nv.getHeso().trim());
                txtNgaynghir.setText(nv.getSongaynghi().trim());
                txtTHuong.setText(nv.getThuong().trim());
                txtTongNhan.setText(nv.getTong().trim());
                txtGiotangca.setText(nv.getGiotangca().trim());
                // setup ảnh của nhân viên
                try {
                        byte[] img = nv.getImg();
                        ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(txtanh.getWidth(), txtanh.getHeight(), Image.SCALE_SMOOTH));
                        txtanh.setIcon(imageicon);  
                        txtcanhbao_img.setVisible(false);
                    } catch (Exception e) {
                        
                       ImageIcon img_default = new ImageIcon("C:\\Users\\huyb1\\Downloads\\Tải xuống\\nhanvien.jpg");// đường dẫn ảnh mặc định
                       txtanh.setIcon(img_default);
                       txtcanhbao_img.setVisible(true);
                    }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có mã " + txtMaNV.getText());
                this.btnNhapmoiActionPerformed(evt);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void cboPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhongBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPhongBanActionPerformed

    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
        txtMaNV.setText("");
        txtMail.setText("");
        buttonGroup1.clearSelection();
        txtHoten.setText("");
        txtSdt.setText("");
        txtDiachi.setText("");
        jdate.setDate(new Date(0));
        cboPhongBan.setSelectedIndex(0);
        cboChucvu.setSelectedIndex(0);
        txtLuongcoban.setText("");
        txtHeso.setText("");
        txtGiotangca.setText("");
        txtNgaynghir.setText("");
        txtTHuong.setText("");
        txtTongNhan.setText("");
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !");
            txtMaNV.setBackground(Color.yellow);
            txtMaNV.requestFocus();
            return;
        } else {
            txtMaNV.setBackground(Color.white);
        }

        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtMaNV.getText());
            NhanVien_Model nvm = new NhanVien_Model();
            if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa nhân viên " + txtMaNV.getText(), "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (nvm.xoa(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công !");
                } else {
                    JOptionPane.showMessageDialog(this, "Không thành công !");
                }
            }
            // load lại show data bên table
            dataTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !");
            txtMaNV.setBackground(Color.yellow);
            txtMaNV.requestFocus();
            return;
        } else {
            txtMaNV.setBackground(Color.white);
        }
        if (txtSdt.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "SĐT không vượt 10 ký tự !");
            txtSdt.setBackground(Color.yellow);
            txtSdt.requestFocus();
            return;
        }
        try {
            int sdt = Integer.parseInt(txtSdt.getText());
            txtSdt.setBackground(Color.white);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "SĐT phải là số !");
            txtSdt.setBackground(Color.yellow);
            txtSdt.requestFocus();
            return;
        }

        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtMaNV.getText());
            nv.setHoten(txtHoten.getText());
            nv.setDiachi(txtDiachi.getText());
            nv.setSdt(txtSdt.getText());
            nv.setEmail(txtMail.getText());
            nv.setPhongban(cboPhongBan.getSelectedItem().toString());
            nv.setGioitinh(rdbNam.isSelected() ? 1 : 0);
            //Chuyển từ java.util.Date sang  java.sql.Date  => stackoverflow.com
            java.util.Date chuachuyen = jdate.getDate();
            java.sql.Date sqlDate;
            sqlDate = new java.sql.Date(chuachuyen.getTime());
            nv.setNgaysinh(sqlDate);

            nv.setChucvu(cboChucvu.getSelectedItem().toString());
            nv.setLuongcoban(txtLuongcoban.getText());
            nv.setHeso(txtHeso.getText());
            nv.setGiotangca(txtGiotangca.getText());
            nv.setSongaynghi(txtNgaynghir.getText());
            nv.setThuong(txtTHuong.getText());
            txtTHuongActionPerformed(evt); // Gọi hàm tính tổng lương ai rảnh đâu code nữa
            nv.setTong(txtTongNhan.getText());
            
            nv.setImg(person_img);// person_img đang rỗng ảnh chưa được chọn nên chưa thể lấy ra

            NhanVien_Model nvm = new NhanVien_Model();
            nvm.capnhat(nv);
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công !");
            // load lại show data bên table
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thành công !" + e.getMessage());
            System.out.println("" + e);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtMaNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !");
            txtMaNV.setBackground(Color.yellow);
            txtMaNV.requestFocus();
            return;
        } else {
            txtMaNV.setBackground(Color.white);
        }
        if (txtSdt.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "SĐT không vượt 10 ký tự !");
            txtSdt.setBackground(Color.yellow);
            txtSdt.requestFocus();
            return;
        } else {
            txtSdt.setBackground(Color.white);
        }
        try {
            int sdt = Integer.parseInt(txtSdt.getText());
            txtSdt.setBackground(Color.white);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "SĐT phải là số !");
            txtSdt.setBackground(Color.yellow);
            txtSdt.requestFocus();
            return;
        }
        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtMaNV.getText());
            nv.setHoten(txtHoten.getText());
            nv.setDiachi(txtDiachi.getText());
            nv.setSdt(txtSdt.getText());
            nv.setEmail(txtMail.getText());
            nv.setPhongban(cboPhongBan.getSelectedItem().toString());
            nv.setGioitinh(rdbNam.isSelected() ? 1 : 0);
            //Chuyển từ java.util.Date sang  java.sql.Date  => stackoverflow.com
            java.util.Date chuachuyen = jdate.getDate();
            java.sql.Date sqlDate;
            sqlDate = new java.sql.Date(chuachuyen.getTime());
            nv.setNgaysinh(sqlDate);
            nv.setChucvu(cboChucvu.getSelectedItem().toString());
            nv.setLuongcoban(txtLuongcoban.getText());
            nv.setHeso(txtHeso.getText());
            nv.setGiotangca(txtGiotangca.getText());
            nv.setSongaynghi(txtNgaynghir.getText());
            nv.setThuong(txtTHuong.getText());
            txtTHuongActionPerformed(evt);// Gọi hàm tính tổng lương cho nhanh
            nv.setTong(txtTongNhan.getText());
            nv.setImg(person_img);
            
            NhanVien_Model nvm = new NhanVien_Model();
            nvm.them(nv);
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công !");
            // load lại show data bên table
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thành công !" + e.getMessage());
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTHuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTHuongActionPerformed
        int luongcb = Integer.parseInt(txtLuongcoban.getText());
        int thuong = Integer.parseInt(txtTHuong.getText());
        int he = Integer.parseInt(txtHeso.getText());
        int tangca = Integer.parseInt(txtGiotangca.getText());
        int ngaynghi = Integer.parseInt(txtNgaynghir.getText());
        txtTongNhan.setText(String.valueOf(luongcb * he + thuong + (tangca * 150000) - (ngaynghi * 200000)));
    }//GEN-LAST:event_txtTHuongActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int row = tblNhanVien.getSelectedRow();
        if (row >= 0) {
            String ma = (String) tblNhanVien.getValueAt(row, 0);
            for (NhanVien nv : listNV) {
                if (nv.getMaNV().equals(ma)) {
                    txtMaNV.setText(nv.getMaNV());
                    txtDiachi.setText(nv.getDiachi());
                    txtHoten.setText(nv.getHoten());
                    txtMail.setText(nv.getEmail());
                    txtSdt.setText(nv.getSdt().trim());
                    if (nv.getGioitinh() == 1) {
                        rdbNam.setSelected(true);
                    } else {
                        rdbNu.setSelected(true);
                    }
                    jdate.setDate(nv.getNgaysinh());
                    cboPhongBan.setSelectedItem(nv.getPhongban());
                    cboChucvu.setSelectedItem(nv.getChucvu());
                    txtLuongcoban.setText(nv.getLuongcoban().trim());
                    txtHeso.setText(nv.getHeso().trim());
                    txtNgaynghir.setText(nv.getSongaynghi().trim());
                    txtTHuong.setText(nv.getThuong().trim());
                    txtTongNhan.setText(nv.getTong().trim());
                    txtGiotangca.setText(nv.getGiotangca().trim());
                    try {
                        byte[] img = nv.getImg();
                        ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(txtanh.getWidth(), txtanh.getHeight(), Image.SCALE_SMOOTH));
                        txtanh.setIcon(imageicon);  
                        txtcanhbao_img.setVisible(false);
                    } catch (Exception e) {
                        
                       ImageIcon img_default = new ImageIcon("C:\\Users\\huyb1\\Downloads\\Tải xuống\\nhanvien.jpg");// ảnh mặc định
                       txtanh.setIcon(img_default);
                       txtcanhbao_img.setVisible(true);
                    }
                    
                    return;
                }
            }
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

   
    private void btnChonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonanhActionPerformed
        JFileChooser chooser = new JFileChooser("C:\\Users\\huyb1\\OneDrive\\Hình ảnh\\icon JAVA"); // đường dẫn đến thư mục ảnh của nhân viên
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(txtanh.getWidth(), txtanh.getHeight(), Image.SCALE_SMOOTH));
        txtanh.setIcon(imageicon);
        // Chuyển ảnh thành dữ liệu byte để lưu và sql
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int i; (i=fis.read(buf))!= -1;){
                bos.write(buf, 0, i);
            }
            person_img = bos.toByteArray();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnChonanhActionPerformed
// Hàm nhấn enter để tìm kiếm
    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        btnTimkiemActionPerformed(evt);
    }//GEN-LAST:event_txtMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonanh;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucvu;
    private javax.swing.JComboBox<String> cboPhongBan;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JPanel tabThongtin;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtGiotangca;
    private javax.swing.JTextField txtHeso;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLuongcoban;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNgaynghir;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTHuong;
    private javax.swing.JTextField txtTongNhan;
    private javax.swing.JLabel txtanh;
    private javax.swing.JLabel txtcanhbao_img;
    // End of variables declaration//GEN-END:variables
}
